services:
  web:
    build: .
    container_name: fraoverstebenk
    restart: unless-stopped
    security_opt:
      - no-new-privileges:true
    env_file:
      - .env
    networks:
      - proxy
    volumes:
      - ./content:/app/content:ro
      - ./static:/app/static:ro
    labels:
      - "traefik.enable=true"
      - "traefik.http.routers.fraoverstebenk.entrypoints=https"
      - "traefik.http.routers.fraoverstebenk.rule=Host(`xn--fraverstebenk-dnb.no`) || Host(`www.xn--fraverstebenk-dnb.no`)"
      - "traefik.http.routers.fraoverstebenk.tls=true"
      - "traefik.http.routers.fraoverstebenk.tls.certresolver=http"
      - "traefik.http.routers.fraoverstebenk.middlewares=fraoverstebenk-www,fraoverstebenk-compress"
      - "traefik.http.middlewares.fraoverstebenk-compress.compress=true"
      - "traefik.http.middlewares.fraoverstebenk-www.redirectregex.regex=^https?://www\\.(.+)"
      - "traefik.http.middlewares.fraoverstebenk-www.redirectregex.replacement=https://$${1}"
      - "traefik.http.middlewares.fraoverstebenk-www.redirectregex.permanent=true"
      - "traefik.http.services.fraoverstebenk.loadbalancer.server.port=8000"

networks:
  proxy:
    external: true
